# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20131222173353) do

  create_table "algorithms", force: true do |t|
    t.integer  "user_id"
    t.text     "code"
    t.string   "save_name"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "conferences", force: true do |t|
    t.integer "conference_code"
    t.string  "name"
    t.string  "subdivision"
    t.integer "year"
  end

  create_table "games", force: true do |t|
    t.integer  "game_code"
    t.date     "date"
    t.integer  "visit_team_code"
    t.integer  "home_team_code"
    t.integer  "stadium_code"
    t.string   "site"
    t.integer  "week"
    t.integer  "year"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "performances", force: true do |t|
    t.integer  "year"
    t.integer  "date"
    t.integer  "team_code"
    t.integer  "game_code"
    t.integer  "rush_att"
    t.integer  "rush_yard"
    t.integer  "rush_td"
    t.integer  "pass_att"
    t.integer  "pass_comp"
    t.integer  "pass_yard"
    t.integer  "pass_td"
    t.integer  "pass_int"
    t.integer  "pass_conv"
    t.integer  "kickoff_ret"
    t.integer  "kickoff_ret_yard"
    t.integer  "kickoff_ret_td"
    t.integer  "punt_ret"
    t.integer  "punt_ret_yard"
    t.integer  "punt_ret_td"
    t.integer  "fum_ret"
    t.integer  "fum_ret_yard"
    t.integer  "fum_ret_td"
    t.integer  "int_ret"
    t.integer  "int_ret_yard"
    t.integer  "int_ret_td"
    t.integer  "misc_ret"
    t.integer  "misc_ret_yard"
    t.integer  "misc_ret_td"
    t.integer  "field_goal_att"
    t.integer  "field_goal_made"
    t.integer  "off_xp_kick_att"
    t.integer  "off_xp_kick_made"
    t.integer  "off_2xp_att"
    t.integer  "off_2xp_made"
    t.integer  "def_2xp_att"
    t.integer  "def_2xp_made"
    t.integer  "safety"
    t.integer  "points"
    t.integer  "punt"
    t.integer  "punt_yard"
    t.integer  "kickoff"
    t.integer  "kickoff_yard"
    t.integer  "kickoff_touchback"
    t.integer  "kickoff_out_of_bounds"
    t.integer  "kickoff_onside"
    t.integer  "fumble"
    t.integer  "fumble_lost"
    t.integer  "tackle_solo"
    t.integer  "tackle_assist"
    t.integer  "tackle_for_loss"
    t.integer  "tackle_for_loss_yard"
    t.integer  "sack"
    t.integer  "sack_yard"
    t.integer  "qb_hurry"
    t.integer  "fumble_forced"
    t.integer  "pass_broken_up"
    t.integer  "kick_punt_blocked"
    t.integer  "first_down_rush"
    t.integer  "first_down_pass"
    t.integer  "first_down_penalty"
    t.integer  "time_of_possession"
    t.integer  "penalty"
    t.integer  "penalty_yard"
    t.integer  "third_down_att"
    t.integer  "third_down_conv"
    t.integer  "fourth_down_att"
    t.integer  "fourth_down_conv"
    t.integer  "red_zone_att"
    t.integer  "red_zone_td"
    t.integer  "red_zone_field_goal"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "seasons", force: true do |t|
    t.integer "year"
    t.integer "num_weeks"
  end

  create_table "share_rankings", force: true do |t|
    t.integer  "year"
    t.integer  "r1"
    t.integer  "r2"
    t.integer  "r3"
    t.integer  "r4"
    t.integer  "r5"
    t.integer  "r6"
    t.integer  "r7"
    t.integer  "r8"
    t.integer  "r9"
    t.integer  "r10"
    t.integer  "r11"
    t.integer  "r12"
    t.integer  "r13"
    t.integer  "r14"
    t.integer  "r15"
    t.integer  "r16"
    t.integer  "r17"
    t.integer  "r18"
    t.integer  "r19"
    t.integer  "r20"
    t.integer  "r21"
    t.integer  "r22"
    t.integer  "r23"
    t.integer  "r24"
    t.integer  "r25"
    t.integer  "r26"
    t.integer  "r27"
    t.integer  "r28"
    t.integer  "r29"
    t.integer  "r30"
    t.integer  "r31"
    t.integer  "r32"
    t.integer  "r33"
    t.integer  "r34"
    t.integer  "r35"
    t.integer  "r36"
    t.integer  "r37"
    t.integer  "r38"
    t.integer  "r39"
    t.integer  "r40"
    t.integer  "r41"
    t.integer  "r42"
    t.integer  "r43"
    t.integer  "r44"
    t.integer  "r45"
    t.integer  "r46"
    t.integer  "r47"
    t.integer  "r48"
    t.integer  "r49"
    t.integer  "r50"
    t.integer  "r51"
    t.integer  "r52"
    t.integer  "r53"
    t.integer  "r54"
    t.integer  "r55"
    t.integer  "r56"
    t.integer  "r57"
    t.integer  "r58"
    t.integer  "r59"
    t.integer  "r60"
    t.integer  "r61"
    t.integer  "r62"
    t.integer  "r63"
    t.integer  "r64"
    t.integer  "r65"
    t.integer  "r66"
    t.integer  "r67"
    t.integer  "r68"
    t.integer  "r69"
    t.integer  "r70"
    t.integer  "r71"
    t.integer  "r72"
    t.integer  "r73"
    t.integer  "r74"
    t.integer  "r75"
    t.integer  "r76"
    t.integer  "r77"
    t.integer  "r78"
    t.integer  "r79"
    t.integer  "r80"
    t.integer  "r81"
    t.integer  "r82"
    t.integer  "r83"
    t.integer  "r84"
    t.integer  "r85"
    t.integer  "r86"
    t.integer  "r87"
    t.integer  "r88"
    t.integer  "r89"
    t.integer  "r90"
    t.integer  "r91"
    t.integer  "r92"
    t.integer  "r93"
    t.integer  "r94"
    t.integer  "r95"
    t.integer  "r96"
    t.integer  "r97"
    t.integer  "r98"
    t.integer  "r99"
    t.integer  "r100"
    t.integer  "r101"
    t.integer  "r102"
    t.integer  "r103"
    t.integer  "r104"
    t.integer  "r105"
    t.integer  "r106"
    t.integer  "r107"
    t.integer  "r108"
    t.integer  "r109"
    t.integer  "r110"
    t.integer  "r111"
    t.integer  "r112"
    t.integer  "r113"
    t.integer  "r114"
    t.integer  "r115"
    t.integer  "r116"
    t.integer  "r117"
    t.integer  "r118"
    t.integer  "r119"
    t.integer  "r120"
    t.integer  "r121"
    t.integer  "r122"
    t.integer  "r123"
    t.integer  "r124"
    t.integer  "r125"
    t.integer  "r126"
    t.integer  "r127"
    t.integer  "r128"
    t.integer  "r129"
    t.integer  "r130"
    t.integer  "r131"
    t.integer  "r132"
    t.integer  "r133"
    t.integer  "r134"
    t.integer  "r135"
    t.integer  "r136"
    t.integer  "r137"
    t.integer  "r138"
    t.integer  "r139"
    t.integer  "r140"
    t.integer  "r141"
    t.integer  "r142"
    t.integer  "r143"
    t.integer  "r144"
    t.integer  "r145"
    t.integer  "r146"
    t.integer  "r147"
    t.integer  "r148"
    t.integer  "r149"
    t.integer  "r150"
    t.integer  "r151"
    t.integer  "r152"
    t.integer  "r153"
    t.integer  "r154"
    t.integer  "r155"
    t.integer  "r156"
    t.integer  "r157"
    t.integer  "r158"
    t.integer  "r159"
    t.integer  "r160"
    t.integer  "r161"
    t.integer  "r162"
    t.integer  "r163"
    t.integer  "r164"
    t.integer  "r165"
    t.integer  "r166"
    t.integer  "r167"
    t.integer  "r168"
    t.integer  "r169"
    t.integer  "r170"
    t.integer  "r171"
    t.integer  "r172"
    t.integer  "r173"
    t.integer  "r174"
    t.integer  "r175"
    t.integer  "r176"
    t.integer  "r177"
    t.integer  "r178"
    t.integer  "r179"
    t.integer  "r180"
    t.integer  "r181"
    t.integer  "r182"
    t.integer  "r183"
    t.integer  "r184"
    t.integer  "r185"
    t.integer  "r186"
    t.integer  "r187"
    t.integer  "r188"
    t.integer  "r189"
    t.integer  "r190"
    t.integer  "r191"
    t.integer  "r192"
    t.integer  "r193"
    t.integer  "r194"
    t.integer  "r195"
    t.integer  "r196"
    t.integer  "r197"
    t.integer  "r198"
    t.integer  "r199"
    t.integer  "r200"
    t.integer  "r201"
    t.integer  "r202"
    t.integer  "r203"
    t.integer  "r204"
    t.integer  "r205"
    t.integer  "r206"
    t.integer  "r207"
    t.integer  "r208"
    t.integer  "r209"
    t.integer  "r210"
    t.integer  "r211"
    t.integer  "r212"
    t.integer  "r213"
    t.integer  "r214"
    t.integer  "r215"
    t.integer  "r216"
    t.integer  "r217"
    t.integer  "r218"
    t.integer  "r219"
    t.integer  "r220"
    t.integer  "r221"
    t.integer  "r222"
    t.integer  "r223"
    t.integer  "r224"
    t.integer  "r225"
    t.integer  "r226"
    t.integer  "r227"
    t.integer  "r228"
    t.integer  "r229"
    t.integer  "r230"
    t.integer  "r231"
    t.integer  "r232"
    t.integer  "r233"
    t.integer  "r234"
    t.integer  "r235"
    t.integer  "r236"
    t.integer  "r237"
    t.integer  "r238"
    t.integer  "r239"
    t.integer  "r240"
    t.integer  "r241"
    t.integer  "r242"
    t.integer  "r243"
    t.integer  "r244"
    t.integer  "r245"
    t.integer  "r246"
    t.integer  "r247"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "shares", force: true do |t|
    t.integer  "user_id"
    t.text     "code"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "teams", force: true do |t|
    t.integer  "team_code"
    t.string   "name"
    t.integer  "conference_code"
    t.integer  "year"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "users", force: true do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.string   "current_sign_in_ip"
    t.string   "last_sign_in_ip"
    t.integer  "current_alg_id"
    t.boolean  "is_admin"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  add_index "users", ["email"], name: "index_users_on_email", unique: true
  add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true

end
